# Standard library imports
import csv
import os
import re

# Third party imports
import colored
from colored import stylize
from jinja2 import Environment, FileSystemLoader, PackageLoader, meta

# Console text highlight color parameters
red_text = colored.fg("red") + colored.attr("bold")
green_text = colored.fg("green") + colored.attr("bold")
blue_text = colored.fg("steel_blue_1b") + colored.attr("bold")
orange_text = colored.fg("dark_orange") + colored.attr("bold")

# Retrieve Jinja2 template for generating EdgeConnect Preconfig YAML file
ec_template_file = "./templates/ec_preconfig_template.jinja2"

# List to populate with variables from Jinja Template
preconfig_vars = []

# Read Jinja Template
with open(ec_template_file, 'r') as jinja:
    data=jinja.readlines()

# Search each line for variable
for line in data:
    result = re.search(r"\['(.*?)'\]", line)
    # Add to preconfig_vars if variable exists and has not yet been added
    if result != None and result.group(1) not in preconfig_vars:
        preconfig_vars.append(result.group(1))



# Write list as headers to csv file

# Local directory for configuration outputs
local_config_directory = "preconfig_outputs/"

if not os.path.exists(local_config_directory):
    os.makedirs(local_config_directory)

# CSV Template generated by Jinja Template
csv_filename = 'preconfig-template.csv'

with open(local_config_directory + csv_filename, 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter=',')
    writer.writerow(preconfig_vars)
