applianceInfo:
  hostname: DEDHAM-SDW01
  group: ACX-ZTP-DEMO
  site: DEDHAM
  networkRole: non-hub
  region: 
  location:
    address: 4 Harvard Drive
    address2: 
    city: Dedham
    state: MA
    zipCode: 2026
    country: US
  contact:
    name: john doe
    email: jdoe@company.tld
    phoneNumber: "123-555-1234"

templateGroups:
  groups:
    - Default Template Group
    - Global ZBFW Policy
    - Global-Store
    - ZTP_QOS_DEMO
    

businessIntentOverlays:
    overlays:
    - REALTIME
    - GUEST
    - CRITICAL
    

deploymentInfo:
  deploymentMode: inline-router
  totalOutboundBandwidth: 30000
  totalInboundBandwidth: 30000
  shapeInboundTraffic: true
  passThroughShapedTraffic:
    outboundMaxBandwidth: 30000

  deploymentInterfaces:

    - interfaceName: lan0
      interfaceType: lan
      interfaceComment: mgmt net
      ipAddressMask: 10.102.254.1/27


    - interfaceName: lan1
      interfaceType: lan
      interfaceComment: ACX BGP Peer
      ipAddressMask: 10.102.90.1/29


    - interfaceName: lan2
      interfaceType: lan
      interfaceComment: Guest
      ipAddressMask: 10.102.30.1/24
      segment: Guest
      zone: Guest
    



    - interfaceName: wan0
      interfaceType: wan
      interfaceComment: Internet
      interfaceLabel: INET
      outboundMaxBandwidth: 30000
      inboundMaxBandwidth: 30000
      firewallMode: statefulSNAT
      behindNat: none
      zone: Public


  dhcpInfo:

  

    - dhcpInterfaceName: lan0
      dhcpType: server
      dhcpAddressMask: 10.102.254.0/27
      startIpAddress: 10.102.254.2
      endIpAddress: 10.102.254.5
      gatewayIpAddress: 10.102.254.1
      dnsServers:
        - 10.1.20.20
        - 8.8.8.8
      ntpServers:
        - 204.2.134.163
      maximumLease: 24
      defaultLease: 24
      options:
        - option: 66
          value:  10.1.40.100
      
        - option: 67
          value:  DEDHAM-SWT01.cfg
      


    

    - dhcpInterfaceName: lan2
      dhcpType: server
      dhcpAddressMask: 10.102.30.0/24
      startIpAddress: 10.102.30.10
      endIpAddress: 10.102.30.100
      gatewayIpAddress: 10.102.30.1
      dnsServers:
        - 8.8.8.8
        - 1.1.1.1
      ntpServers:
        - 204.2.134.163
      maximumLease: 24
      defaultLease: 24
      options:

localRoutes:
  useSharedSubnetInfo: true
  advertiseLocalLanSubnets: true
  advertiseLocalWanSubnets: false
  localMetric: 50
  localCommunities:
  redistOspfToSubnetShare: false
  ospfRedistMetric: 0
  ospfRedistTag: 0
  filterRoutesWithLocalASN: true
  redistToSDwanFabricRouteMap: "allow_bgp_rtmap_to_subsh"
  

ecLicensing:

  useDefaultAccount: true
  bandwidthLevel: base
  boost: 5000


bgpSystemConfig:
  enable: true
  asn: 65120
  routerId: 10.102.90.1
  enableGracefulRestart: false
  maxRestartTime: 120
  maxStalePathTime: 150
  redistToSilverPeak: true
  propagateAsPath: true
  redistOspfToBgp: false
  filterTag: 0

  neighbors:
    - peerIpAddress: 10.102.90.2
      enableImports: true
      peerAsn: 65121
      peerType: Branch
      enableNeighbor: true
      nextHopSelf: false
      inboundRouteMap : default_rtmap_bgp_inbound_br
      outboundRouteMap : default_rtmap_bgp_outbound_br
      keepAlive: 30
      holdTime: 90
      password:
